export const TEMPLATES = [
  // --- SIGNATURE LAYER ---
  { 
    id: "loom-oak", 
    plate: "004", 
    name: "Loom Oak", 
    style: "Signature", 
    booth: "Oak", 
    formatLabel: "2×6 Strip", 
    layout: "strip-3", 
    font: "Newsreader", 
    ratio: {w: 1, h: 3},
    desc: "Three frames on unbleached ground with a single gilt seam — the warp line of the loom drawn straight down the strip.",
    paper: "#ECE7DB", 
    slot: "#D1CBBF", 
    edge: "#8A7350", 
    ink: "#161311", 
    accent: "#8A7350", 
    sName: "AMARA & SEBASTIAN", 
    sSub: "OCTOBER · LONG BEACH" 
  },
  { 
    id: "bituin", 
    plate: "011", 
    name: "Bituin", 
    style: "Signature", 
    booth: "Oak", 
    formatLabel: "4×6 Postcard", 
    layout: "pv-2", 
    font: "Newsreader", 
    ratio: {w: 2, h: 3},
    desc: "Leaf-black ground, two apertures in geometric tension, one champagne thread bisecting the field below.",
    paper: "#1A1714", 
    slot: "#241F1B", 
    edge: "#8F8C8A", 
    ink: "#E8E1D3", 
    accent: "#DCCBB5", 
    sName: "RENZO & CAMILLE", 
    sSub: "NOVEMBER · CARSON" 
  },
  { 
    id: "calado-pina", 
    plate: "019", 
    name: "Calado Piña", 
    style: "Signature", 
    booth: "Oak", 
    formatLabel: "4×6 Postcard", 
    layout: "pv-2", 
    font: "Cormorant Garamond", 
    ratio: {w: 2, h: 3},
    desc: "Two openings on raw piña fiber, divided by a hand-stitched calado — openwork drawn the way grandmothers drew it.",
    paper: "#E3DEC5", 
    slot: "#D2CBBF", 
    edge: "#8F8C8A", 
    ink: "#161311", 
    accent: "#8A7350", 
    sName: "Marisol & Diego", 
    sSub: "September · Pasadena" 
  },
  { 
    id: "sombra-twin", 
    plate: "027", 
    name: "Sombra Twin", 
    style: "Signature", 
    booth: "White", 
    formatLabel: "6×4 Square", 
    layout: "pc-2-sq", 
    font: "Cormorant Garamond", 
    ratio: {w: 3, h: 2},
    desc: "Twin squares with breathing room, each trailing a ghost silhouette offset behind it, as if seen through fabric.",
    paper: "#D2CBBF", 
    slot: "#C0B9AC", 
    edge: "#8F8C8A", 
    ink: "#161311", 
    accent: "#8A7350", 
    sName: "SOFIA & MARCO", 
    sSub: "SEPTEMBER · LOS ANGELES" 
  },
  { 
    id: "katha-heritage-frame", 
    plate: "033", 
    name: "Abel & Calado", 
    style: "Signature", 
    booth: "Oak", 
    formatLabel: "4×6 Postcard", 
    layout: "pv-2", 
    font: "Fraunces", 
    ratio: {w: 2, h: 3},
    desc: "Double fine-lined frame in Champagne Heirloom with Fraunces serif set on a Piña Ecru ground.",
    paper: "#E8E1D3", 
    slot: "#F5EFE4", 
    edge: "#C4B59D", 
    ink: "#241E1A", 
    accent: "#C4B59D", 
    sName: "Abel & Calado", 
    sSub: "OCTOBER · MALIBU" 
  },
  
  { id: "fn-1", isFootnote: true, text: "Calado Piña — openwork drawn from Barong Tagalog embroidery, 17th c." },

  // --- CLASSIC LAYER ---
  { 
    id: "iron-rule", 
    plate: "041", 
    name: "Iron Rule", 
    style: "Classic", 
    booth: "White", 
    formatLabel: "2×6 Strip", 
    layout: "strip-4", 
    font: "Newsreader", 
    ratio: {w: 1, h: 3},
    desc: "Four frames, one hairline rule. The design steps back so the portrait carries the whole strip.",
    paper: "#FAFAF8", 
    slot: "#ECE7DB", 
    edge: "#8F8C8A", 
    ink: "#161311", 
    accent: "#8F8C8A", 
    sName: "NADIA + ELIAS", 
    sSub: "JULY · LONG BEACH" 
  },
  { 
    id: "champagne-frame", 
    plate: "053", 
    name: "Champagne Frame", 
    style: "Classic", 
    booth: "Oak", 
    formatLabel: "4×6 Postcard", 
    layout: "pv-2", 
    font: "Newsreader", 
    ratio: {w: 2, h: 3},
    desc: "A concentric pewter border around two portraits — restraint with a single quiet line.",
    paper: "#ECE7DB", 
    slot: "#D1CBBF", 
    edge: "#8F8C8A", 
    ink: "#161311", 
    accent: "#8F8C8A", 
    sName: "JAMES & ELEANOR", 
    sSub: "OCTOBER · MALIBU" 
  },
  { 
    id: "wedding-luxe-gold", 
    plate: "062", 
    name: "Tradition Gold", 
    style: "Classic", 
    booth: "White", 
    formatLabel: "2×6 Strip", 
    layout: "strip-3", 
    font: "Cinzel", 
    ratio: {w: 1, h: 3},
    desc: "Double gold foil fine outline detailing around each slot. Clean Roman serif display, providing timeless heirloom appeal.",
    paper: "#FAF6F0", 
    slot: "#F4EDE3", 
    edge: "#C5A85C", 
    ink: "#544634", 
    accent: "#C5A85C", 
    sName: "LENA & THEO", 
    sSub: "JULY · CARSON" 
  },
  { 
    id: "rose-whisper", 
    plate: "075", 
    name: "Rose Whisper", 
    style: "Classic", 
    booth: "White", 
    formatLabel: "4×6 Postcard", 
    layout: "pv-2", 
    font: "Playfair Display", 
    ratio: {w: 2, h: 3},
    desc: "Deckled ivory paper backdrop adorned with a hand-sketched classic cream and white rose nested gracefully above the text.",
    paper: "#FAF9F6", 
    slot: "#EDEDE9", 
    edge: "#EBE9E4", 
    ink: "#292524", 
    accent: "#A59E92", 
    sName: "Ines & Rafael", 
    sSub: "June · Long Beach" 
  },
  { 
    id: "wedding-warm-terracotta", 
    plate: "088", 
    name: "Warm Umber", 
    style: "Classic", 
    booth: "Oak", 
    formatLabel: "2×6 Strip", 
    layout: "strip-4", 
    font: "EB Garamond", 
    ratio: {w: 1, h: 3},
    desc: "Bohemian dry umber clay ground. Accentuated by fine hairline gold rules and micro leafy contours.",
    paper: "#7A5A3E", 
    slot: "#846248", 
    edge: "#DEC190", 
    ink: "#FCFAF7", 
    accent: "#E3CE9F", 
    sName: "MIRA & JONAS", 
    sSub: "AUGUST · IRVINE" 
  },

  { id: "fn-2", isFootnote: true, text: "The Classic Standard — 1px hairlines. The portrait carries the weight." }
];

// Real catalog — content.json is the SSOT (scraped from client.kathabooth.com 2026-07-02, Jed-confirmed).
// Names/prices/order mirror the live HoneyBook form; do not alter.
export const DEFAULT_TIER_ID = "glam_editorial";

export const TIERS = [
  { id: "editorial", name: "Editorial Installation", booth: "Oak Booth", format: "2×6 or 4×6", price: "$949", desc: "Oak wood DSLR installation with professional-grade photography and Metallic Pearl proprietary prints.", flag: null, available: true },
  { id: "glam_editorial", name: "Glam Editorial Installation", booth: "Oak Booth", format: "2×6 or 4×6", price: "$1,149", desc: "The full Editorial installation with professional monochrome, skin-soothing photography.", flag: "Flagship", available: true },
  { id: "architectural", name: "Architectural Installation", booth: "White Booth", format: "2×6 or 4×6", price: "$749", desc: "Architectural booth configuration with prints. Temporarily unavailable.", flag: "Currently Unavailable", available: false },
  { id: "katha_booth", name: "Katha Booth Installation", booth: "Essential Booth", format: "2×6", price: "$549", desc: "The essential Katha booth — four hours of unlimited high-grade photos, GIFs, and instant sharing.", flag: "Essential", available: true }
];
